### ISSUE TITLE
Need a Web client

### ISSUE THREAD

**Issue by zensh** [seccom/kpass#1]
第一个服务端可运行版本 https://github.com/seccom/kpass/releases/tag/v0.1.0

设计特性：
1. 该应用分成运行程序和数据库两个文件，在终端运行时直接打开浏览器界面进行相关操作；
2. 支持多用户 `user`，每个用户的加密信息 `entry` 独立；
3. 支持团队 `team`，团队可以添加多个用户，共享团队内的加密信息；
4. 支持对外分享某一条个人的或者团队的加密信息；
5. 信息 `entry` 不被加密，每一条信息可包含多个加密组 `secret`，加密组支持四个字段 `name`、`url`、`password`、`note`，加密段的内容完全被加密。
6. 超强加密模式，无论是用户口令、团队口令还是加密组，都被口令 (pass)、id、数据库初始化 salt、随机数据等进行了多重加密。数据库虽然为文本模式，但从其中不可能还原口令或者加密组内容。但口令是解密信息的关键，如果入侵者拿到了完整数据库并知道了用户名和口令，就能取得该用户名下的所有信息。

目前支持：
1. 用户注册 `POST /join`
2. 用户登录 `POST /login`，取得 `access_token` 进行下一操作
3. 读取用户信息列表 `GET /entries`
4. 创建一条信息 `POST /entries`
5. 在一条信息中增加加密段 `POST /entries/:entryId/secrets`
6. 读取一条完整的信息 `GET /entries/:entryId`，里面包含了解密出来的密文段

更多说明见 https://github.com/seccom/kpass/blob/master/pkg/router.go

**Comment by zensh** [comment]
@DavidCai1993 @eshujiushiwo @suyu34

**Comment by suyu34** [comment]
我来了

**Comment by isayme** [comment]
我也在玩一个, 用的lastpass方案...

**Comment by zensh** [comment]
@isayme 这个主要是本地或局域网内，虽然也能完全在线，但不打算往那个方向做。另外就是支持个人和团队，支持对内会对外共享

**Comment by zensh** [comment]
`v1.0.0-alpha.1` 即将来临， @SuneBear 👍
